services:

  master:
    build:
      context: ./master
    ports:
      - "8000:8000"
    container_name: master-server
    networks:
      - gfs_net

  chunkserver1:
    build: ./chunkserver
    container_name: chunkserver1
    ports:
      - "8001:8000"
    environment:
      - CHUNKSERVER_ID=chunkserver1
      - EXTERNAL_HOST=localhost       # frontend can access via localhost
      - EXTERNAL_PORT=8001            # external mapped port
      - MASTER_URL=http://master:8000
    networks:
      - gfs_net
    depends_on:
      - master

  chunkserver2:
    build:
      context: ./chunkserver
    container_name: chunkserver2
    ports:
      - "8002:8000"
    environment:
      - CHUNKSERVER_ID=chunkserver2
      - EXTERNAL_HOST=localhost
      - EXTERNAL_PORT=8002
      - MASTER_URL=http://master:8000
    networks:
      - gfs_net

  chunkserver3:
    build:
      context: ./chunkserver
    container_name: chunkserver3
    ports:
      - "8003:8000"
    environment:
      - CHUNKSERVER_ID=chunkserver3
      - EXTERNAL_HOST=localhost
      - EXTERNAL_PORT=8003
      - MASTER_URL=http://master:8000
    networks:
      - gfs_net

  chunkserver4:
    build:
      context: ./chunkserver
    container_name: chunkserver4
    ports:
      - "8004:8000"
    environment:
      - CHUNKSERVER_ID=chunkserver4
      - EXTERNAL_HOST=localhost
      - EXTERNAL_PORT=8004
      - MASTER_URL=http://master:8000
    networks:
      - gfs_net

  chunkserver5:
    build:
      context: ./chunkserver
    container_name: chunkserver5
    ports:
      - "8005:8000"
    environment:
      - CHUNKSERVER_ID=chunkserver5
      - EXTERNAL_HOST=localhost
      - EXTERNAL_PORT=8005
      - MASTER_URL=http://master:8000
    networks:
      - gfs_net

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - master
    container_name: frontend
    networks:
      - gfs_net

networks:
  gfs_net:
    driver: bridge
