

services:

  master:
    build:
      context: ./master
    ports:
      - "8000:8000"
    container_name: master-server
    networks:
      - gfs_net
  chunkserver1:
    build:
      context: ./chunkserver
    ports:
      - "8001:8000"
    networks:
      - gfs_net
    environment:
      - CHUNKSERVER_ID=chunkserver1

  chunkserver2:
    build:
      context: ./chunkserver
    ports:
      - "8002:8000"
    networks:
      - gfs_net
    environment:
      - CHUNKSERVER_ID=chunkserver2

  chunkserver3:
    build:
      context: ./chunkserver
    ports:
      - "8003:8000"
    networks:
      - gfs_net
    environment:
      - CHUNKSERVER_ID=chunkserver3

  chunkserver4:
    build:
      context: ./chunkserver
    ports:
      - "8004:8000"
    networks:
      - gfs_net
    environment:
      - CHUNKSERVER_ID=chunkserver4

  chunkserver5:
    build:
      context: ./chunkserver
    ports:
      - "8005:8000"
    networks:
      - gfs_net
    environment:
      - CHUNKSERVER_ID=chunkserver5

    

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - master
    container_name: frontend
    networks:
      - gfs_net

networks:
  gfs_net:
    driver: bridge
